name: Android Debug Build
on:
  push:
    branches: [ "dev", "feature/*", "bugfix/*" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  debugBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x apps/android/gradlew
      
    - name: Build Debug APK
      run: |
        cd apps/android
        ./gradlew assembleDebug --stacktrace
      env:
        JAVA_OPTS: "--enable-native-access=ALL-UNNAMED"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: apps/android/app/build/outputs/apk/debug/*.apk
