name: Android Release Build
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  debugBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.17.1
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x apps/android/gradlew

      - name: Build Debug APK with NX
        run: |
          pnpm nx run @elara/android:release

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: apps/android/app/build/outputs/apk/release/*.apk
